# Site setings
name: 'Alec Harmon'
description: 'Sometimes I sit and write code and sometimes I just sit'
# Sidebar about text
site_description: 'Sometimes I sit and write code and sometimes I just sit'
logo:
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://alecharmon.com/
disqus: 
mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
# Add your GA Tracking Id
ga_analytics: 

# Contact form setings
email: alecharmon@outlook.com

thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: 'harmon_alec'
# facebook: 'username'
github: 'alecharmon'
# codepen: 'username'
# dribbble: 'username'
# medium: '@username'
# instagram: 'username'
# pinterest: 'username'
linkedin: 'alecharmon'

# Navigation
navigation:
  - text: About
    url: /about/
  # - text: Style Guide
  #   url: /style-guide/
  - text: Contact Me
    url: /contact/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-author-page

# Pagination
paginate: 6
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
